{{- if and .Values.env.manage (not .Values.env.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "savvy.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savvy.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  .env_config: |
    {{- include "savvy.envFile" . | nindent 4 }}
{{- end }}
